### ISSUE TITLE
Error starting

### ISSUE THREAD

**Issue by planet4** [BorisBrock/Sunalyzer#85]
Thanks for sharing this. I have used the premium for Solarweb before but dropped it a while back. Exited to try this. However I can not start the container. Have tried with different users as well as root. Not sure what I have missed.

I also wonder what will happen with the data before it was started. If I get this up and running. I have all data since 2019 in Solarweb as well as PV output. I suppose the datalogger in Fronius only pulls new data. Is there a way to import the history?

2024-10-11 06:46:45,521 INFO spawned: 'server' with pid 13
2024-10-11 06:46:45,647 WARN exited: grabber (exit status 0; not expected)
2024-10-11 06:46:45,951 WARN exited: server (exit status 0; not expected)
2024-10-11 06:46:48,957 INFO spawned: 'grabber' with pid 14
2024-10-11 06:46:48,960 INFO spawned: 'server' with pid 15
2024-10-11 06:46:49,081 WARN exited: grabber (exit status 0; not expected)
2024-10-11 06:46:49,331 INFO gave up: grabber entered FATAL state, too many start retries too quickly
2024-10-11 06:46:49,384 WARN exited: server (exit status 0; not expected)
2024-10-11 06:46:49,385 WARN received SIGQUIT indicating exit request
2024-10-11 06:46:49,385 INFO waiting for processes to die
2024-10-11 06:46:51,388 WARN stopped: processes (terminated by SIGTERM)
/usr/local/lib/python3.12/site-packages/supervisor/options.py:474: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  self.warnings.warn(
2024-10-11 06:46:52,722 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2024-10-11 06:46:52,725 INFO supervisord started with pid 1
2024-10-11 06:46:53,728 INFO spawned: 'processes' with pid 7
2024-10-11 06:46:53,730 INFO spawned: 'grabber' with pid 8
2024-10-11 06:46:53,733 INFO spawned: 'server' with pid 9
2024-10-11 06:46:53,847 WARN exited: grabber (exit status 0; not expected)

**Comment by planet4** [comment]
Also did some changes after I installed supervisor.

PermissionError: [Errno 13] Permission denied: '/supervisord.log'
Traceback (most recent call last):
  File "/usr/local/bin/supervisord", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/supervisor/supervisord.py", line 359, in main
    go(options)
  File "/usr/local/lib/python3.12/site-packages/supervisor/supervisord.py", line 369, in go

**Comment by BorisBrock** [comment]
Regarding your startup issue:

- Have you provided a data folder with read/write access to the container?
- Does the data folder contain a valid config.yaml? Can you check the file for syntax errors and/or share it here?
- Also there should be .log files in the data folder, once the container starts up. Do you see any? What's inside?

Regarding historic data:

There is no automated solution for this. But it should be possible with a little effort and some Python :-)

- Sunalyzer uses a simple sqlite database to store its data
- So if you run it for a minute, you should have a nice little DB with some example data in it
- Take this DB from the data folder and put it somewhere local
- Use SQLiteBrowser (or a similar tool), to see how the DB is organized
- Then write a python script, which reads in your historic data and stores it in the SQLite DB
- Put the DB back in your data folder and start up Sunalyzer
- Now all data should be there

This will of course take some time/effort, but it shouldn't be too hard.

**Comment by planet4** [comment]
I did some chmod changes on the supervisor.sock file and also changed the conf file. Not really sure what fixed it but it works now running as root.

I think my Python skills are to limited to solve this. Maybe someone else will fix this in the future and share.
